name = "ai-quran-workers"
main= "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NEURON_LIMITER"
id = "<your-kv-id>"

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "<your-kv-id>"
